import { act, fireEvent, render, screen, within } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { NextIntlClientProvider } from 'next-intl'
import messages from '@/messages/en.json'
import { SplitPreview } from '../preview/SplitPreview'
const text = messages.teskeid.receiptSplitPreview
function setup() { render(<NextIntlClientProvider locale="en" messages={messages}><SplitPreview /></NextIntlClientProvider>) }
async function settle() { await act(async () => { await vi.advanceTimersByTimeAsync(150) }) }
beforeEach(() => vi.useFakeTimers())
afterEach(() => { vi.useRealTimers() })
describe('synthetic standalone split UI', () => {
  it('shows the isolated preview banner, separate totals and inline explanation', () => {
    setup()
    expect(screen.getByText(text.previewHelp)).toBeInTheDocument()
    expect(screen.getByText('Missing from the items: EUR 4')).toBeInTheDocument()
    expect(within(screen.getByRole('article', { name: 'Menabrea' })).getByText('Beer')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /Fully claimed \(1\)/ })).toHaveAttribute('aria-expanded', 'false')
    expect(screen.queryByRole('article', { name: 'Water' })).not.toBeInTheDocument()
  })
  it('sets half a bottle rather than adding halves, and preserves selected quantities after saving', async () => {
    setup()
    const wine = within(screen.getByRole('article', { name: 'Red wine' }))
    fireEvent.click(wine.getByRole('button', { name: '½' }))
    fireEvent.click(wine.getByRole('button', { name: '½' }))
    expect(wine.getByLabelText(text.otherQuantity)).toHaveValue('0.5')
    fireEvent.click(wine.getByRole('button', { name: text.saveQuantity }))
    await settle()
    expect(wine.getByText(/Stebbi · ½/)).toBeInTheDocument()
    expect(wine.getByText('½ of 1 remaining')).toBeInTheDocument()
  })
  it('keeps the drawer open through refresh and shows participant results outside collapsed groups', () => {
    setup()
    const drawer = screen.getByRole('button', { name: /Fully claimed/ })
    fireEvent.click(drawer)
    expect(screen.getByRole('article', { name: 'Water' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: text.refresh }))
    expect(drawer).toHaveAttribute('aria-expanded', 'true')
    fireEvent.click(drawer)
    fireEvent.click(screen.getByRole('button', { name: /Björn ·/ }))
    expect(screen.getByRole('article', { name: 'Water' })).toBeInTheDocument()
    expect(screen.queryByRole('article', { name: 'Red wine' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: text.clear }))
    expect(screen.getByRole('button', { name: /Fully claimed/ })).toHaveAttribute('aria-expanded', 'false')
  })
  it('retains dirty text and rejects stale saves when a simulated update arrives', async () => {
    setup()
    const wine = within(screen.getByRole('article', { name: 'Red wine' }))
    const input = wine.getByLabelText(text.otherQuantity)
    act(() => input.focus())
    fireEvent.change(input, { target: { value: '1/3' } })
    fireEvent.click(screen.getByRole('button', { name: text.simulate }))
    await act(async () => { await vi.advanceTimersByTimeAsync(8000) })
    expect(input).toHaveValue('1/3')
    expect(input).toHaveFocus()
    expect(wine.getByRole('alert')).toHaveTextContent(text.stale)
    expect(wine.getByRole('button', { name: text.saveQuantity })).toBeDisabled()
    fireEvent.click(wine.getByRole('button', { name: text.reloadLine }))
    expect(wine.getByLabelText(text.otherQuantity)).toHaveValue('0')
  })
  it('keeps fully claimed row visible until a focused draft is resolved', async () => {
    setup()
    const wine = within(screen.getByRole('article', { name: 'Red wine' }))
    fireEvent.click(wine.getByRole('button', { name: '½' }))
    fireEvent.click(wine.getByRole('button', { name: text.saveQuantity }))
    await settle()
    const input = wine.getByLabelText(text.otherQuantity)
    act(() => input.focus())
    fireEvent.change(input, { target: { value: '1/3' } })
    fireEvent.click(screen.getByRole('button', { name: text.simulate }))
    fireEvent.click(screen.getByRole('button', { name: text.refresh }))
    expect(screen.getByRole('article', { name: 'Red wine' })).toBeInTheDocument()
    expect(input).toHaveFocus()
    fireEvent.click(wine.getByRole('button', { name: text.reloadLine }))
    expect(screen.queryByRole('article', { name: 'Red wine' })).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: /Fully claimed \(2\)/ })).toBeInTheDocument()
  })
  it('starts review with a mismatch and permits starting the split', async () => {
    setup()
    fireEvent.click(screen.getByRole('button', { name: text.resetReview }))
    expect(screen.getByText('Missing from the items: EUR 4')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: text.start }))
    await settle()
    expect(screen.queryByRole('button', { name: text.start })).not.toBeInTheDocument()
    expect(within(screen.getByRole('article', { name: 'Red wine' })).getByRole('button', { name: '⅓' })).toBeEnabled()
  })
  it('hides all owner edits when viewing as another participant', () => {
    setup()
    fireEvent.change(screen.getByLabelText(text.viewAs), { target: { value: 'anna' } })
    expect(screen.queryByRole('button', { name: text.edit })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: text.editReceipt })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: text.add })).not.toBeInTheDocument()
  })
})
